guild check
Jintaku/Jintaku-Cogs-V3 pull request #35
Opened 2020-08-29 07:24 UTC by phenom4n4n

Adds guild checks to the commands that need them and also randomizes embed colors since that looks better than black.

2020-08-29 17:52 UTC, lionirdeadman requested changes
Otherwise looks good, will need to test.

2020-08-29 17:52 UTC, lionirdeadman commented on conversationgames/conversationgames.py
> +        await ctx.send(embed=randomize_colour(embed))
I think the randomize_colour shouldn't be used, can you remove that from the PR?

2020-08-29 21:58 UTC, phenom4n4n commented
Done.

2020-08-30 16:44 UTC, lionirdeadman approved these changes

2020-08-30 16:47 UTC, merged

2020-08-30 16:47 UTC, lionirdeadman commented
Thanks!